STR = {"searchByID": "Search and hit Enter to execute",
       "pickNode": "Enter ID or select using mouse",
       "enterState": "Enter state",
       "noConditions": "No conditions specified",
       "noExecution": "The interactive execution mode is unavailable, retrying..."
};

chartNames = {
    "messagesSent": "Messages Sent (#)",
    "messagesReceived": "Messages Received (#)",
    "signalMessagesReceived": "Signal Messages Received (#)",
    "otherMessagesReceived": "Other Messages Received (#)",
    "requestMessagesReceived": "Request Messages Received (#)",
    "continueMessagesReceived": "Continue Messages Received (#)",
    "bulkSignalMessagesReceived": "Bulk Signal Messages Received (#)",
    "heartbeatMessagesReceived": "Heartbeat Messages Received (#)",
    "receiveTimeoutMessagesReceived": "Timeout Messages Received (#)",
    "outgoingEdgesAdded": "Outgoing Edges Added (#)",
    "outgoingEdgesRemoved": "Outgoing Edges Removed (#)",
    "numberOfOutgoingEdges": "Number of Outgoing Edges (#)",
    "verticesRemoved": "Vertices Removed (#)",
    "verticesAdded": "Vertices Added (#)",
    "numberOfVertices": "Number of Vertices (#)",
    "signalOperationsExecuted": "Signal Operations Executed (#)",
    "collectOperationsExecuted": "Collect Operations Executed (#)",
    "toCollectSize": "To Collect Size (#)",
    "toSignalSize": "To Signal Size (#)",
    "workerId": "Worker ID",
    "runtime_cores": "Available Processors (#)",
    "jmx_system_load": "System CPU Load (%)",
    "jmx_process_time": "Process CPU Time (NS)",
    "jmx_process_load": "Process CPU Load (%)",
    "jmx_swap_free": "Free Swap Space Size (B)",
    "jmx_swap_total": "Total Swap Space Size (B)",
    "jmx_mem_total": "Total Physical Memory Size (B)",
    "jmx_mem_free": "Free Physical Memory Size (B)",
    "jmx_committed_vms": "Committed Virtual Memory Size (B)",
    "runtime_mem_max": "Max Memory (B)",
    "runtime_mem_free": "Free Memory (B)",
    "runtime_mem_total": "Total Memory (B)",
};
